[package]
name = "polyminis-server"
version = "0.1.0"
authors = ["Ricardo Sisnett<sisnett@polyminis.com>"]

polyminis-core = { path = "polyminis-core" }

env_logger = "0.3.2"
lru-cache = "0.1.0"
log = "0.3.6"
rustful = "0.9"
